# -*- coding: utf-8 -*-
"""main_news_article

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyrKab86h0MWByFZ8_b3d17tkKEanFTf
"""

!pip install -r /content/requirement.txt

!pip install pyngrok
from pyngrok import ngrok
!ngrok update

from google.colab import userdata
ngrok_auth_token=userdata.get('authotoken_key')

ngrok.set_auth_token(ngrok_auth_token)

import os
from threading import Thread

def run_streamlit():
  os.system('streamlit run /content/llm_news_articles.py --server.port 8501')

thread=Thread(target=run_streamlit)
thread.start()

public_url=ngrok.connect(8501)
print(public_url)